config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  # get 'pages/about'  = localhost:3000/pages/about 
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"

  get "blog", to: redirect("www.austenstaski-taski.herokuapp.com")

  # custom route created to localhost:3000/about 
  resources :projects do
    resources :tasks, except: [:index], controller: 'projects/tasks'
  end

  root "pages#home"

  get "*path", to: redirect("pages#error")
  
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counter.rb
class Counter
  def self.calculate_percent_complete(completed_tasks, total_tasks)
    completed_tasks.to_f / total_tasks.to_f * 100 
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  # Has to be here to assoicate tasks with projects
  after_initialize :set_defaults
  # Integrate validations
  validates_presence_of :title, :description, :percent_complete
   # Custom scopes
  scope :almost_completed, -> { where('percent_complete > 75.0') }
  scope :still_needs_some_work, -> { where('percent_complete < 75.0') }
  # Add defaults
  def set_defaults
    self.percent_complete ||= 0.0
  end
  # Integrate callbacks
  # Integrate database relationships
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  after_save :update_percent_complete if :mark_completed?

  scope :completed, -> { where(completed: true) }

  mount_uploader :task_file, TaskFileUploader

  def mark_completed?
    self.completed == true
  end

  def update_percent_complete
    project = Project. find(self.project_id)
    count_of_completed_tasks = project.tasks.completed.count
    count_of_total_tasks = project.tasks.count
    project.update!(percent_complete: Counter.calculate_percent_complete(count_of_completed_tasks, count_of_total_tasks))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  	@title = "My Starter Webpage"
  end

  def home
  	@projects = Project.all.limit(100)
  	# You usually want to limit how many records you pull from the database
  end

  def error
  end
  
end

app/controllers/projects/tasks_controller.rb
class Projects::TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :new, :create, :edit, :update, :destroy]

  def show

  end

  def new
    @task = Task.new
  end

  def edit
  
  end

  def create
    @task = Task.new(task_params)
    @task.project_id = @project.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_url(@task.project_id), notice: "Task was created successfully!"}
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_url(@task.project_id), notice: "Task was updated successfully!"}
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: "Task was deleted successfully!"}
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :project_id, :completed, :task_file)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Congrats! You created a new project!' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'You have successfully updated the project.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'The project was successfully deleted!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def show

  end

  def new
    @task = Task.new
  end

  def edit
  
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was created successfully!"}
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new}
        format.json { render json: @task.errors, status: :unprocessable_entity }
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was updated successfully!"}
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new}
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@task.project_id), notice: "Task was deleted successfully!"}
      format.json { head :no_content }
    end
  end

  private

  def set_task
    # TODO
  end

  def task_params
    # TODO
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taski</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <div>
    <%= image_tag("logos/logo.jpg", height: '100px', width: '100%')  %>
  </div>
  <%= render "shared/nav" %>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<hr>
<p><%= @title %></p>

app/views/pages/contact.html.erb
<h1>Contact Me</h1>
<p>Contact Me!a;osidgja;osidgjna;kdslm</p>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist</h1>

Go back to <%= link_to "homepage", root_path %>

app/views/pages/home.html.erb
<h1>Home Page</h1>

<hr>
<div class="homepage-projects">	
	<%= render "shared/projects" %>
</div>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <hr>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Percent complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %> | </td>
        <td><%= project.description %> | </td>
        <td><%= project.percent_complete %> | </td>
        <td><%= link_to 'Show', project, id: "link" %> | </td>
        <td><%= link_to 'Edit', edit_project_path(project), id: "link" %> | </td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, id: "link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path, id: "link" %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<br>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <div class="pipe"><%= @project.title %></div>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Percent complete:</strong>
  <%= @project.percent_complete %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<hr>

<h2>Tasks for project</h2>

<% @tasks.each do |task| %>

  <p><%= link_to task.title, project_task_path(@project.id, task.id) %></p>

<% end %>

<% if current_user %>

<%= link_to "Add a new Task for this project", new_project_task_path(project_id: @project.id) %>

<% end %>

app/views/projects/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <%= pluralize(@task.errors.count, "error") %> prohibited this project from being saved:

    <% @task.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.label "Attachment" %>
  <%= f.file_field :task_file %>

  <%= f.submit %>

<% end %>

app/views/projects/tasks/edit.html.erb
<%= render 'form' %>

app/views/projects/tasks/new.html.erb
<%= render 'form' %>

app/views/projects/tasks/show.html.erb
<hr>

<h3><%= @task.title %></h3>

<p><%= @task.description %></p>

<h4>Task started: <%= @task.created_at %></h4>

<% if @task.created_at != @task.updated_at %>
  <h4>Updated: <%= @task.updated_at %></h4>
<% end %>

<% if @task.completed == true %>
  <p><em>Task is completed.</em></p>
<% else %>
  <p><em>Task is pending.</em></p>
<% end %>

<% if !@task.task_file.blank? %>
<p><%= link_to "Attachment", @task.task_file.to_s %></p>
<% end %>

<%= link_to "Edit", edit_project_task_path(@task.project_id, @task.id) %>

<hr>

<%= link_to "Back to Project", project_path(@task.project_id) %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<div class="navbar">
<%= link_to "Home •", root_path, id: "navlink" %>
	<%= link_to "About •", about_path, id: "navlink" %>
	<%= link_to "Contact •", contact_path, id: "navlink" %>
	<%= link_to "Blog •", blog_path, id: "navlink" %>
	<%= link_to "Projects •", projects_path, id: "navlink" %>

<% if current_user %>
  <%= link_to "Sign Out •", destroy_user_session_path, method: :delete, id: "navlink" %>
  <%= link_to "Edit Account", edit_user_registration_path, id: "navlink" %>
<% else %>
  <%= link_to "Register •", new_user_registration_path, id: "navlink" %> 
  <%= link_to "Sign In", new_user_session_path, id: "navlink" %> 
<% end %>
</div>

app/views/shared/_projects.html.erb
<% if current_user %>
<% @projects.each do |project| %>
	<p><strong><%= project.title %></strong> - <em><%= project.description %><em> <%= " | #{project.percent_complete}" if project.percent_complete %> <!-- <%= project.percent_complete %> Will print -nil if there is no value. How it's coded now will not print it if it's blank --> </p>
<% end %>
<% end %>
<!-- The <%= %> prints to page but <% %> does not -->